[package]
name = "async-experiments"
version = "0.1.0"
authors = ["Adam Cigánek <adam.ciganek@gmail.com>"]

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs" }
maidsafe_utilities = "~0.9.0"
rand = "~0.3.14"
thread-id = "~2.0.0"
unwrap = "~1.1.0"